config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "/up" => "rails/health#show", as: :rails_health_check

  get "/security.txt" => redirect("https://vdp.cabinetoffice.gov.uk/.well-known/security.txt")
  get "/.well-known/security.txt" => redirect("https://vdp.cabinetoffice.gov.uk/.well-known/security.txt")

  root "groups#index"

  get "/sign-up" => "authentication#sign_up", as: :sign_up
  get "/sign-out" => "authentication#sign_out", as: :sign_out
  get "/sign-in" => "authentication#sign_in", as: :sign_in

  scope "auth/:provider" do
    match "/callback" => "authentication#callback_from_omniauth", via: %i[get post]
  end

  scope "forms/:form_id" do
    get "/" => "forms#show", as: :form
    get "/change-name" => "forms/change_name#edit", as: :change_form_name
    post "/change-name" => "forms/change_name#update"

    scope "/live" do
      get "/" => "forms/live#show_form", as: :live_form
      get "/pages" => "forms/live#show_pages", as: :live_form_pages
    end

    scope "/archived" do
      get "/" => "forms/archived#show_form", as: :archived_form
      get "/pages" => "forms/archived#show_pages", as: :archived_form_pages
    end

    get "/submission-email" => "forms/submission_email#new", as: :submission_email_input
    post "/submission-email" => "forms/submission_email#create"
    get "/confirm-submission-email" => "forms/submission_email#submission_email_code", as: :submission_email_code
    post "/confirm-submission-email" => "forms/submission_email#confirm_submission_email_code", as: :confirm_submission_email_code
    get "/submission-email-confirmed" => "forms/submission_email#submission_email_confirmed", as: :submission_email_confirmed
    get "/email-code-sent" => "forms/submission_email#submission_email_code_sent", as: :submission_email_code_sent

    get "/delete" => "forms/delete_confirmation#delete", as: :delete_form
    delete "/delete" => "forms/delete_confirmation#destroy", as: :destroy_form
    get "/archive" => "forms/archive_form#archive", as: :archive_form
    post "/archive" => "forms/archive_form#update", as: :archive_form_update
    get "/archive-success" => "forms/archive_form#confirmation", as: :archive_form_confirmation
    get "/privacy-policy" => "forms/privacy_policy#new", as: :privacy_policy
    post "/privacy-policy" => "forms/privacy_policy#create"
    get "/make-live" => "forms/make_live#new", as: :make_live
    post "/make-live" => "forms/make_live#create", as: :make_live_create
    get "/unarchive" => "forms/unarchive#new", as: :unarchive
    post "/unarchive" => "forms/unarchive#create", as: :unarchive_create
    get "/what-happens-next" => "forms/what_happens_next#new", as: :what_happens_next
    post "/what-happens-next" => "forms/what_happens_next#create", as: :what_happens_next_create
    post "/what-happens-next-preview" => "forms/what_happens_next#render_preview", as: :what_happens_next_render_preview
    get "/contact-details" => "forms/contact_details#new", as: :contact_details
    post "/contact-details" => "forms/contact_details#create", as: :contact_details_create
    get "/declaration" => "forms/declaration#new", as: :declaration
    post "/declaration" => "forms/declaration#create", as: :declaration_create
    get "/payment-link" => "forms/payment_link#new", as: :payment_link
    post "/payment-link" => "forms/payment_link#create", as: :payment_link_create
    get "/receive-csv" => "forms/receive_csv#new", as: :receive_csv
    post "/receive-csv" => "forms/receive_csv#create", as: :receive_csv_create
    get "/share-preview" => "forms/share_preview#new", as: :share_preview
    post "/share-preview" => "forms/share_preview#create", as: :share_preview_create

    scope "/pages" do
      get "/" => "pages#index", as: :form_pages
      post "/" => "forms#mark_pages_section_completed"
      post "/move-page" => "pages#move_page", as: :move_page

      scope "/new" do
        get "/start-new-question" => "pages#start_new_question", as: :start_new_question
        get "/guidance" => "pages/guidance#new", as: :guidance_new
        post "/guidance" => "pages/guidance#create", as: :guidance_create
        post "/guidance-preview" => "pages/guidance#render_preview", as: :guidance_render_preview
        get "/type-of-answer" => "pages/type_of_answer#new", as: :type_of_answer_new
        post "/type-of-answer" => "pages/type_of_answer#create", as: :type_of_answer_create
        get "/text-settings" => "pages/text_settings#new", as: :text_settings_new
        post "/text-settings" => "pages/text_settings#create", as: :text_settings_create
        get "/date-settings" => "pages/date_settings#new", as: :date_settings_new
        post "/date-settings" => "pages/date_settings#create", as: :date_settings_create
        get "/selection/type" => "pages/long_lists_selection/type#new", as: :long_lists_selection_type_new
        post "/selection/type" => "pages/long_lists_selection/type#create", as: :long_lists_selection_type_create
        get "/selection/options" => "pages/long_lists_selection/options#new", as: :long_lists_selection_options_new
        post "/selection/options" => "pages/long_lists_selection/options#create", as: :long_lists_selection_options_create
        get "/selection/bulk-options" => "pages/long_lists_selection/bulk_options#new", as: :long_lists_selection_bulk_options_new
        post "/selection/bulk-options" => "pages/long_lists_selection/bulk_options#create", as: :long_lists_selection_bulk_options_create
        get "/address-settings" => "pages/address_settings#new", as: :address_settings_new
        post "/address-settings" => "pages/address_settings#create", as: :address_settings_create
        get "/name-settings" => "pages/name_settings#new", as: :name_settings_new
        post "/name-settings" => "pages/name_settings#create", as: :name_settings_create
        get "/question_text" => "pages/question_text#new", as: :question_text_new
        post "/question_text" => "pages/question_text#create", as: :question_text_create
        get "/question" => "pages/questions#new", as: :new_question
        post "/question" => "pages/questions#create", as: :create_question
      end

      get "/new-condition" => "pages/conditions#routing_page", as: :routing_page
      post "/new-condition" => "pages/conditions#set_routing_page", as: :set_routing_page

      scope "/:page_id" do
        scope "/conditions" do
          get "/new" => "pages/conditions#new", as: :new_condition
          post "/new" => "pages/conditions#create", as: :create_condition
          get "/:condition_id" => "pages/conditions#edit", as: :edit_condition
          put "/:condition_id" => "pages/conditions#update", as: :update_condition
          get "/:condition_id/delete" => "pages/conditions#delete", as: :delete_condition
          delete "/:condition_id/delete" => "pages/conditions#destroy", as: :destroy_condition
        end

        scope "/routes" do
          get "/" => "pages/routes#show", as: :show_routes
          get "/any-other-answer/questions-to-skip/new" => "pages/secondary_skip_#new", as: :new_secondary_skip
          post "/any-other-answer/questions-to-skip/new" => "pages/secondary_skip_#create", as: :create_secondary_skip
          get "/any-other-answer/questions-to-skip" => "pages/secondary_skip_#edit", as: :edit_secondary_skip
          post "/any-other-answer/questions-to-skip" => "pages/secondary_skip_#update", as: :update_secondary_skip
          get "/any-other-answer/questions-to-skip/delete" => "pages/secondary_skip_#delete", as: :delete_secondary_skip
          delete "/any-other-answer/questions-to-skip/delete" => "pages/secondary_skip_#destroy", as: :destroy_secondary_skip
        end

        scope "/edit" do
          get "/type-of-answer" => "pages/type_of_answer#edit", as: :type_of_answer_edit
          post "/type-of-answer" => "pages/type_of_answer#update", as: :type_of_answer_update
          get "/text-settings" => "pages/text_settings#edit", as: :text_settings_edit
          post "/text-settings" => "pages/text_settings#update", as: :text_settings_update
          get "/date-settings" => "pages/date_settings#edit", as: :date_settings_edit
          post "/date-settings" => "pages/date_settings#update", as: :date_settings_update
          get "/selection/type" => "pages/long_lists_selection/type#edit", as: :long_lists_selection_type_edit
          post "/selection/type" => "pages/long_lists_selection/type#update", as: :long_lists_selection_type_update
          get "/selection/options" => "pages/long_lists_selection/options#edit", as: :long_lists_selection_options_edit
          post "/selection/options" => "pages/long_lists_selection/options#update", as: :long_lists_selection_options_update
          get "/selection/bulk-options" => "pages/long_lists_selection/bulk_options#edit", as: :long_lists_selection_bulk_options_edit
          post "/selection/bulk-options" => "pages/long_lists_selection/bulk_options#update", as: :long_lists_selection_bulk_options_update
          get "/address-settings" => "pages/address_settings#edit", as: :address_settings_edit
          post "/address-settings" => "pages/address_settings#update", as: :address_settings_update
          get "/name-settings" => "pages/name_settings#edit", as: :name_settings_edit
          post "/name-settings" => "pages/name_settings#update", as: :name_settings_update
          get "/guidance" => "pages/guidance#edit", as: :guidance_edit
          post "/guidance" => "pages/guidance#update", as: :guidance_update
          get "/question" => "pages/questions#edit", as: :edit_question
          post "/question" => "pages/questions#update", as: :update_question
        end

        scope "/delete" do

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :organisation

  belongs_to :creator, class_name: "User", optional: true

  belongs_to :upgrade_requester, class_name: "User", optional: true

  default_scope { order("LOWER(name)", :created_at) }

  has_many :memberships, dependent: :destroy do
    def ordered
      joins(:user).order("users.name")
    end
  end
  has_many :users, through: :memberships do
    def group_admins
      where(memberships: { role: "group_admin" })
    end
  end

  has_many :group_forms, dependent: :restrict_with_exception

  scope :for_user, ->(user) { joins(:memberships).where(memberships: { user_id: user.id }) }

  scope :for_organisation, ->(organisation) { where(organisation:) }

  validates :name, presence: true, uniqueness: { scope: :organisation_id }
  before_create :set_external_id

  enum :status, { trial: "trial", active: "active", upgrade_requested: "upgrade_requested" }, validate: true

  def to_param
    external_id
  end

private

  def set_external_id
    self.external_id = ExternalIdProvider.generate_id
  end
end

app/models/group_form.rb
class GroupForm < ApplicationRecord
  self.primary_key = %i[form_id group_id]
  self.table_name = :groups_form_ids

  belongs_to :group

  def form
    Form.find(form_id)
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, except: %i[index new create]
  after_action :verify_authorized, except: :index
  after_action :verify_policy_scoped, only: :index

  # GET /groups
  def index
    if @current_user.super_admin?
      @search_input = OrganisationSearchInput.new({ organisation_id: @current_user.organisation_id }.merge(search_params))

      @active_groups = policy_scope(Group).where(organisation_id: @search_input.organisation_id).active
      @upgrade_requested_groups = policy_scope(Group).where(organisation_id: @search_input.organisation_id).upgrade_requested
      @trial_groups = policy_scope(Group).where(organisation_id: @search_input.organisation_id).trial
    else
      @active_groups = policy_scope(Group).active
      @upgrade_requested_groups = policy_scope(Group).upgrade_requested
      @trial_groups = policy_scope(Group).trial
    end
  end

  # GET /groups/1
  def show
    authorize @group
    forms = @group.group_forms.map(&:form)
    @form_list_presenter = FormListPresenter.call(forms:, group: @group) unless forms.empty?
  end

  # GET /groups/new
  def new
    @group = Group.new
    authorize @group
  end

  # GET /groups/1/edit
  def edit
    authorize @group
  end

  # POST /groups
  def create
    @group = Group.new(group_params.merge({ creator: @current_user }))
    @group.organisation = current_user.organisation
    @group.memberships.build(user: current_user, added_by: current_user, role: :group_admin)

    authorize @group

    if @group.save
      redirect_to @group
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /groups/1
  def update
    authorize @group
    if @group.update(group_params)
      success_message = @group.active? ? t("groups.success_messages.update") : nil
      redirect_to @group, success: success_message, status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def confirm_upgrade
    authorize @group, :upgrade?
    @confirm_upgrade_input = Groups::ConfirmUpgradeInput.new
  end

  def upgrade
    authorize @group

    @confirm_upgrade_input = Groups::ConfirmUpgradeInput.new(confirm_upgrade_input_params)
    return render :confirm_upgrade, status: :unprocessable_entity unless @confirm_upgrade_input.valid?
    return redirect_to @group unless @confirm_upgrade_input.confirmed?

    GroupService.new(group: @group, current_user: @current_user, host: request.host).upgrade_group

    redirect_to @group, success: t("groups.success_messages.upgrade"), status: :see_other
  end

  def confirm_upgrade_request
    authorize @group, :request_upgrade?
  end

  def request_upgrade
    authorize @group, :request_upgrade?

    GroupService.new(group: @group, current_user: @current_user, host: request.host).request_upgrade

    render :upgrade_requested
  end

  def review_upgrade
    authorize @group, :review_upgrade?
    @confirm_upgrade_input = Groups::ConfirmUpgradeInput.new
  end

  def submit_review_upgrade
    authorize @group, :review_upgrade?

    @confirm_upgrade_input = Groups::ConfirmUpgradeInput.new(confirm_upgrade_input_params)

    return render :review_upgrade, status: :unprocessable_entity unless @confirm_upgrade_input.valid?

    group_service = GroupService.new(group: @group, current_user: @current_user, host: request.host)
    if @confirm_upgrade_input.confirmed?
      group_service.upgrade_group
      redirect_to @group, success: t("groups.success_messages.upgrade"), status: :see_other
    else
      group_service.reject_upgrade
      redirect_to @group, status: :see_other
    end
  end

private

  # Use callbacks to share common setup or constraints between actions.
  def set_group
    @group = Group.find_by!(external_id: params[:id])
  end

  # Only allow a list of trusted parameters through.
  def group_params
    params.require(:group).permit(:name)
  end

  def confirm_upgrade_input_params
    params.require(:groups_confirm_upgrade_input).permit(:confirm)
  end

  def search_params
    params[:search]&.permit(:organisation_id) || {}
  end
end

app/views/groups/_group.html.erb
<h1 class="govuk-heading-l">
  <span class="govuk-caption-l"><%= t("groups.status_caption.#{group.status}") %></span><span class="govuk-visually-hidden"> - </span>
  <%= group.name %>
</h1>

app/views/groups/confirm_upgrade.html.erb
<% set_page_title(title_with_error_prefix(t('page_titles.group_upgrade'), @confirm_upgrade_input.errors.any?)) %>

<% content_for :back_link, govuk_back_link_to(@group, t("back_link.group", group_name: @group.name)) %>

<div class="govuk-grid-row">
  <div class="govuk-grid-column-two-thirds">
    <%= form_with(model: @confirm_upgrade_input, url: upgrade_group_path(@group)) do |f| %>
      <% if @confirm_upgrade_input&.errors.any? %>
        <%= f.govuk_error_summary %>
      <% end %>

      <h1 class="govuk-heading-l">
        <%= t('page_titles.group_upgrade') %>
      </h1>

      <%= t('.body_html') %>

      <%= f.govuk_collection_radio_buttons :confirm,
                                           @confirm_upgrade_input.values, ->(option) { option }, ->(option) { t('helpers.label.confirm_action_input.options.' + "#{option}") },
                                           legend: { text: t('.radios_legend'), size: 'm' },
                                           inline: true %>

      <%= f.govuk_submit t("save_and_continue") %>
    <% end %>
  </div>
</div>

app/views/groups/confirm_upgrade_request.html.erb
<% set_page_title(t('page_titles.group_confirm_upgrade_request')) %>

<% content_for :back_link, govuk_back_link_to(@group, t("back_link.group", group_name: @group.name)) %>

<div class="govuk-grid-row">
  <div class="govuk-grid-column-two-thirds">
    <%= form_with(url: request_upgrade_group_path(@group), method: 'POST') do |form| %>
      <h1 class="govuk-heading-l">
        <span class="govuk-caption-l"><%= @group.name %></span>
        <%= t('page_titles.group_confirm_upgrade_request') %>
      </h1>

      <%= t("groups.confirm_upgrade_request.body_html")%>

      <%= govuk_inset_text do %>
        <%= t("groups.confirm_upgrade_request.inset_text") %>
      <% end %>

      <%= form.govuk_submit t("groups.confirm_upgrade_request.send_request_to_upgrade") %>
    <% end%>
  </div>
</div>

app/views/groups/edit.html.erb
<% set_page_title(title_with_error_prefix(t(".title"), @group.errors.any?)) %>
<% content_for :back_link, govuk_back_link_to(@group, t("back_link.group", group_name: @group.name)) %>

<%= form_with(model: @group) do |f| %>
<div class="govuk-grid-row">
  <div class="govuk-grid-column-two-thirds">
    <% if @group.errors.any? %>
      <%= f.govuk_error_summary %>
    <% end %>

    <%= f.govuk_text_field :name, label: {  text: t(".title"), tag: 'h1', size: 'l' }, caption: { text: @group.name, size: 'l' } %>

    <%= f.govuk_submit t("save_and_continue") %>
  <% end %>
  </div>
</div>

app/views/groups/index.html.erb
<% set_page_title(t("page_titles.group_index")) %>

<% if @upgrade_requested_groups.present? && (@current_user.organisation_admin? || @current_user.super_admin?)  %>
  <div class="govuk-grid-row">
    <div class="govuk-grid-column-two-thirds">
      <%= govuk_notification_banner(title_text: t("banner.default.title")) do |banner| %>
        <% banner.with_heading(text: t("groups.index.upgrade_requests_banner_heading", count: @upgrade_requested_groups.length)) %>
      <% end %>
    </div>
  </div>
<% elsif @current_user.standard? && !@current_user.current_org_has_mou? %>
  <div class="govuk-grid-row">
    <div class="govuk-grid-column-two-thirds">
      <%= govuk_notification_banner(title_text: t("banner.default.title")) do |banner| %>
        <% banner.with_heading(text: t("groups.index.no_mou_banner.heading"), tag: "h3") %>
        <% t("groups.index.no_mou_banner.body_html", contact_link: contact_link) %>
      <% end %>
    </div>
  </div>
<% end %>

<div class="govuk-grid-row">
  <div class="govuk-grid-column-full">

    <h1 class="govuk-heading-l">
      <%= t("page_titles.group_index") %>
    </h1>

    <% if @current_user.super_admin? %>
      <div class="govuk-!-margin-bottom-4">
        <%= form_with(model: @search_input, scope: :search, url: groups_path, method: 'get', local: true) do |f| %>
          <%= render DfE::Autocomplete::View.new(
            f,
            attribute_name: :organisation_id,
            form_field: f.govuk_collection_select(:organisation_id,
                                                  Organisation.with_users.order(:name),
                                                  :id,
                                                  :name_with_abbreviation,
                                                  class: ['govuk-!-width-three-quarters'],
                                                  options: { prompt: t('groups.index.organisation_search.prompt') },
                                                  label: { text: t('groups.index.organisation_search.label', organisation_name: @search_input.organisation.name), size: 'm', tag: 'h2' },
                                                  hint: { text: t('groups.index.organisation_search.hint') },
                                                  ),
            html_attributes: { 'data-show-all-values' => 'true'},
            )%>
          <%= f.govuk_submit(t("home.change_filter"), secondary: true) %>
        <% end %>
      </div>
    <% end %>

    <%= render GroupListComponent::View.new(groups: @upgrade_requested_groups, title: t('groups.index.upgrade_requests_title'), show_empty: false) %>
    <%= render GroupListComponent::View.new(groups: @active_groups, title: t('groups.index.active_title'), empty_message: t('groups.index.active_empty_message')) %>
    <%= render GroupListComponent::View.new(groups: @trial_groups, title: t('groups.index.trial_title'), empty_message: t('groups.index.trial_empty_message')) %>

    <%= govuk_button_link_to t("groups.index.create_group"), new_group_path, class:"govuk-!-margin-top-3" %>
  </div>
</div>

<div class="govuk-grid-row govuk-!-margin-top-3">
  <div class="govuk-grid-column-two-thirds">
    <%= govuk_details(summary_text: t("groups.index.group_explainer_title")) do
      if @current_user.organisation_admin? || @current_user.super_admin?
        t("groups.index.group_explainer_org_admin_body_html")
      else
        t("groups.index.group_explainer_body_html")
      end
    end %>
  </div>
</div>

<%= init_autocomplete_script(show_all_values: true, raw_attribute: false, source: false) %>

app/views/groups/new.html.erb
<% set_page_title(title_with_error_prefix(t(".title"), @group.errors.any?)) %>
<% content_for :back_link, govuk_back_link_to(groups_path,t("back_link.groups")) %>

<%= form_with(model: @group) do |f| %>
<div class="govuk-grid-row">
  <div class="govuk-grid-column-two-thirds">
    <% if @group.errors.any? %>
      <%= f.govuk_error_summary %>
    <% end %>

    <h1 class="govuk-heading-l"><%= t(".title") %></h1>

    <%= t(".body_html") %>

    <%= f.govuk_text_field :name, label: {  tag: 'h2', size: 'm' } %>

    <%= f.govuk_submit t("save_and_continue") %>
  <% end %>
  </div>
</div>

app/views/groups/review_upgrade.html.erb
<% set_page_title(title_with_error_prefix(t('page_titles.group_review_upgrade'), @confirm_upgrade_input.errors.any?)) %>

<% content_for :back_link, govuk_back_link_to(@group, t("back_link.group", group_name: @group.name)) %>

<div class="govuk-grid-row">
  <div class="govuk-grid-column-two-thirds">
    <%= form_with(model: @confirm_upgrade_input, url: review_upgrade_group_path(@group)) do |f| %>
      <% if @confirm_upgrade_input&.errors.any? %>
        <%= f.govuk_error_summary %>
      <% end %>

      <h1 class="govuk-heading-l">
        <%= t('page_titles.group_review_upgrade') %>
      </h1>

      <%= t('groups.review_upgrade.body_html', upgrade_requester_name: @group.upgrade_requester.name) %>

      <%= f.govuk_collection_radio_buttons :confirm,
                                           @confirm_upgrade_input.values, ->(option) { option }, ->(option) { t('helpers.label.confirm_action_input.options.' + "#{option}") },
                                           legend: { text: t('groups.review_upgrade.radios_legend'), size: 'm' },
                                           inline: true %>

      <%= f.govuk_submit t("save_and_continue") %>
    <% end %>
  </div>
</div>

app/views/groups/show.html.erb
<% set_page_title(@group.name) %>
<% content_for :back_link, govuk_back_link_to(groups_path, t("back_link.groups")) %>

<% unless @group.active? %>
  <div class="govuk-grid-row">
    <div class="govuk-grid-column-two-thirds">
      <%= govuk_notification_banner(title_text: t("banner.default.title")) do |nb| %>
        <% if @group.organisation.mou_signatures.present? %>
          <% if policy(@group).review_upgrade? %>
            <% nb.with_heading(text: t("groups.show.trial_banner.review_upgrade.heading"), tag: "h3") %>
            <%= t("groups.show.trial_banner.review_upgrade.body_html", upgrade_requester_name: @group.upgrade_requester.name) %>
            <%= govuk_link_to t("groups.show.trial_banner.review_upgrade.link"), review_upgrade_group_path(@group) %>
          <% elsif policy(@group).upgrade? %>
            <% nb.with_heading(text: t("groups.show.trial_banner.heading"), tag: "h3") %>
            <%= t("groups.show.trial_banner.upgrade.body_html") %>
            <%= govuk_link_to t("groups.show.trial_banner.upgrade.link"), upgrade_group_path(@group) %>
          <% elsif policy(@group).request_upgrade? %>
            <% nb.with_heading(text: t("groups.show.trial_banner.heading"), tag: "h3") %>
            <%= t("groups.show.trial_banner.request_upgrade.body_html") %>
            <%= govuk_link_to t("groups.show.trial_banner.request_upgrade.link"), request_upgrade_group_path(@group) %>
          <% elsif @group.memberships.find_by(user: @current_user)&.group_admin? && !@group.organisation.admin_users.present? %>
            <% nb.with_heading(text: t("groups.show.trial_banner.heading"), tag: "h3") %>
            <%= t("groups.show.trial_banner.request_upgrade.body_html") %>
            <%= t("groups.show.trial_banner.request_upgrade.without_org_admin_html", contact_link: contact_link) %>
          <% else %>
            <% nb.with_heading(text: t("groups.show.trial_banner.heading"), tag: "h3") %>
            <%= t("groups.show.trial_banner.editor.body_html") %>
          <% end %>
        <% else %>
          <% if @current_user.super_admin? %>
            <% nb.with_heading(text: t("groups.index.no_mou_banner.heading"), tag: "h3") %>
            <%= t("groups.index.no_mou_banner.body_html", contact_link: contact_link) %>
          <% elsif policy(@group).request_upgrade? %>
            <% nb.with_heading(text: t("groups.show.trial_banner.heading"), tag: "h3") %>
            <%= t("groups.show.trial_banner.request_upgrade.body_html") %>
            <%= t("groups.show.trial_banner.request_upgrade.without_mou_signature_html", contact_link: contact_link) %>
          <% else %>
            <% nb.with_heading(text: t("groups.show.trial_banner.heading"), tag: "h3") %>
            <%= t("groups.show.trial_banner.editor.body_html") %>
          <% end %>
        <% end %>
      <% end %>
    </div>
  </div>
<% end %>

<%= render @group %>

<ul class="govuk-list govuk-list--spaced govuk-!-margin-bottom-5">
  <% if policy(@group).edit? %>
    <li><%= govuk_link_to(t(".edit_group_name"), edit_group_path(@group)) %></li>
    <li><%= govuk_link_to(t(".edit_group_members"), group_members_path(@group)) %></li>
  <% else %>
    <li><%= govuk_link_to(t(".review_group_members"), group_members_path(@group)) %></li>
  <% end %>
</ul>

<%= govuk_start_button(text: t("home.create_a_form"), href: new_group_form_path(@group)) %>

<% if @form_list_presenter %>
  <%= govuk_table(**@form_list_presenter.data) %>
<% end %>

app/views/groups/upgrade_requested.html.erb
<% set_page_title(t('page_titles.group_upgrade_requested')) %>

<% content_for :back_link, govuk_back_link_to(@group, t("back_link.group", group_name: @group.name)) %>

<div class="govuk-grid-row">
  <div class="govuk-grid-column-two-thirds">
    <%= govuk_panel(title_text: t("page_titles.group_upgrade_requested")) %>

    <h2 class="govuk-heading-m"><%= t("groups.upgrade_requested.what_happens_next.heading") %></h2>

    <%= t("groups.upgrade_requested.what_happens_next.body_html") %>

    <p>
      <%= govuk_link_to t("back_link.group", group_name: @group.name), group_path(@group) %>
    </p>
  </div>
</div>