config/routes.rb
    get "/make-live" => "forms/make_live#new", as: :make_live
    post "/make-live" => "forms/make_live#create", as: :make_live_create
    get "/unarchive" => "forms/unarchive#new", as: :unarchive
    post "/unarchive" => "forms/unarchive#create", as: :unarchive_create
    get "/what-happens-next" => "forms/what_happens_next#new", as: :what_happens_next
    post "/what-happens-next" => "forms/what_happens_next#create", as: :what_happens_next_create
    post "/what-happens-next-preview" => "forms/what_happens_next#render_preview", as: :what_happens_next_render_preview
    get "/contact-details" => "forms/contact_details#new", as: :contact_details
    post "/contact-details" => "forms/contact_details#create", as: :contact_details_create
    get "/declaration" => "forms/declaration#new", as: :declaration
    post "/declaration" => "forms/declaration#create", as: :declaration_create
    get "/payment-link" => "forms/payment_link#new", as: :payment_link
    post "/payment-link" => "forms/payment_link#create", as: :payment_link_create
    get "/receive-csv" => "forms/receive_csv#new", as: :receive_csv
    post "/receive-csv" => "forms/receive_csv#create", as: :receive_csv_create
    get "/share-preview" => "forms/share_preview#new", as: :share_preview
    post "/share-preview" => "forms/share_preview#create", as: :share_preview_create

    scope "/pages" do
      get "/" => "pages#index", as: :form_pages
      post "/" => "forms#mark_pages_section_completed"
      post "/move-page" => "pages#move_page", as: :move_page

      scope "/new" do
        get "/start-new-question" => "pages#start_new_question", as: :start_new_question
        get "/guidance" => "pages/guidance#new", as: :guidance_new
        post "/guidance" => "pages/guidance#create", as: :guidance_create
        post "/guidance-preview" => "pages/guidance#render_preview", as: :guidance_render_preview
        get "/type-of-answer" => "pages/type_of_answer#new", as: :type_of_answer_new
        post "/type-of-answer" => "pages/type_of_answer#create", as: :type_of_answer_create
        get "/text-settings" => "pages/text_settings#new", as: :text_settings_new
        post "/text-settings" => "pages/text_settings#create", as: :text_settings_create
        get "/date-settings" => "pages/date_settings#new", as: :date_settings_new
        post "/date-settings" => "pages/date_settings#create", as: :date_settings_create
        get "/selection/type" => "pages/long_lists_selection/type#new", as: :long_lists_selection_type_new
        post "/selection/type" => "pages/long_lists_selection/type#create", as: :long_lists_selection_type_create
        get "/selection/options" => "pages/long_lists_selection/options#new", as: :long_lists_selection_options_new
        post "/selection/options" => "pages/long_lists_selection/options#create", as: :long_lists_selection_options_create
        get "/selection/bulk-options" => "pages/long_lists_selection/bulk_options#new", as: :long_lists_selection_bulk_options_new
        post "/selection/bulk-options" => "pages/long_lists_selection/bulk_options#create", as: :long_lists_selection_bulk_options_create
        get "/address-settings" => "pages/address_settings#new", as: :address_settings_new
        post "/address-settings" => "pages/address_settings#create", as: :address_settings_create
        get "/name-settings" => "pages/name_settings#new", as: :name_settings_new
        post "/name-settings" => "pages/name_settings#create", as: :name_settings_create
        get "/question_text" => "pages/question_text#new", as: :question_text_new
        post "/question_text" => "pages/question_text#create", as: :question_text_create
        get "/question" => "pages/questions#new", as: :new_question
        post "/question" => "pages/questions#create", as: :create_question
      end

      get "/new-condition" => "pages/conditions#routing_page", as: :routing_page
      post "/new-condition" => "pages/conditions#set_routing_page", as: :set_routing_page

      scope "/:page_id" do
        scope "/conditions" do
          get "/new" => "pages/conditions#new", as: :new_condition
          post "/new" => "pages/conditions#create", as: :create_condition
          get "/:condition_id" => "pages/conditions#edit", as: :edit_condition
          put "/:condition_id" => "pages/conditions#update", as: :update_condition
          get "/:condition_id/delete" => "pages/conditions#delete", as: :delete_condition
          delete "/:condition_id/delete" => "pages/conditions#destroy", as: :destroy_condition
        end

        scope "/routes" do
          get "/" => "pages/routes#show", as: :show_routes
          get "/any-other-answer/questions-to-skip/new" => "pages/secondary_skip_#new", as: :new_secondary_skip
          post "/any-other-answer/questions-to-skip/new" => "pages/secondary_skip_#create", as: :create_secondary_skip
          get "/any-other-answer/questions-to-skip" => "pages/secondary_skip_#edit", as: :edit_secondary_skip
          post "/any-other-answer/questions-to-skip" => "pages/secondary_skip_#update", as: :update_secondary_skip
          get "/any-other-answer/questions-to-skip/delete" => "pages/secondary_skip_#delete", as: :delete_secondary_skip
          delete "/any-other-answer/questions-to-skip/delete" => "pages/secondary_skip_#destroy", as: :destroy_secondary_skip
        end

        scope "/edit" do
          get "/type-of-answer" => "pages/type_of_answer#edit", as: :type_of_answer_edit
          post "/type-of-answer" => "pages/type_of_answer#update", as: :type_of_answer_update
          get "/text-settings" => "pages/text_settings#edit", as: :text_settings_edit
          post "/text-settings" => "pages/text_settings#update", as: :text_settings_update
          get "/date-settings" => "pages/date_settings#edit", as: :date_settings_edit
          post "/date-settings" => "pages/date_settings#update", as: :date_settings_update
          get "/selection/type" => "pages/long_lists_selection/type#edit", as: :long_lists_selection_type_edit
          post "/selection/type" => "pages/long_lists_selection/type#update", as: :long_lists_selection_type_update
          get "/selection/options" => "pages/long_lists_selection/options#edit", as: :long_lists_selection_options_edit
          post "/selection/options" => "pages/long_lists_selection/options#update", as: :long_lists_selection_options_update
          get "/selection/bulk-options" => "pages/long_lists_selection/bulk_options#edit", as: :long_lists_selection_bulk_options_edit
          post "/selection/bulk-options" => "pages/long_lists_selection/bulk_options#update", as: :long_lists_selection_bulk_options_update
          get "/address-settings" => "pages/address_settings#edit", as: :address_settings_edit
          post "/address-settings" => "pages/address_settings#update", as: :address_settings_update
          get "/name-settings" => "pages/name_settings#edit", as: :name_settings_edit
          post "/name-settings" => "pages/name_settings#update", as: :name_settings_update
          get "/guidance" => "pages/guidance#edit", as: :guidance_edit
          post "/guidance" => "pages/guidance#update", as: :guidance_update
          get "/question" => "pages/questions#edit", as: :edit_question
          post "/question" => "pages/questions#update", as: :update_question
        end

        scope "/delete" do
          get "/" => "forms/delete_confirmation#delete", as: :delete_page
          delete "/" => "forms/delete_confirmation#destroy", as: :destroy_page
        end
      end
    end
  end

  resources :users, only: %i[index edit update]

  post "/act-as/:user_id", to: "act_as_user#start", as: :act_as_user_start
  get "/act-as-stop", to: "act_as_user#stop", as: :act_as_user_stop

  namespace :account do
    resource :name, only: %i[edit update]
    resource :organisation, only: %i[edit update]
    resource :terms_of_use, controller: :terms_of_use, only: %i[edit update]
  end

  resources :mou_signatures, only: %i[index], path: "mous"

  resource :mou_signature, only: %i[new show create], path: "/memorandum-of-understanding" do
    get "/signed", to: "mou_signatures#confirmation", as: :confirmation
  end

  resources :groups, except: :destroy do
    resources :forms, controller: :group_forms, only: %i[new create]
    resources :members, controller: :group_members, only: %i[index new create]
    member do
      get "upgrade", to: "groups#confirm_upgrade"
      post "upgrade", to: "groups#upgrade"

      get "request_upgrade", to: "groups#confirm_upgrade_request"
      post "request_upgrade", to: "groups#request_upgrade"
      get "review_upgrade", to: "groups#review_upgrade"
      post "review_upgrade", to: "groups#submit_review_upgrade"
    end
  end

  resources :memberships, only: %i[destroy update]

  scope :reports do
    get "/", to: "reports#index", as: :reports
    get "features", to: "reports#features", as: :report_features
    get "users", to: "reports#users", as: :report_users
    get "add_another_answer", to: "reports#add_another_answer", as: :report_add_another_answer
    get "last-signed-in-at", to: "reports#last_signed_in_at", as: :report_last_signed_in_at
    get "selection-questions-summary", to: "reports#selection_questions_summary", as: :report_selection_questions_summary
    get "selection-questions-with-autocomplete", to: "reports#selection_questions_with_autocomplete", as: :report_selection_questions_with_autocomplete
    get "selection-questions-with-radios", to: "reports#selection_questions_with_radios", as: :report_selection_questions_with_radios
    get "selection-questions-with-checkboxes", to: "reports#selection_questions_with_checkboxes", as: :report_selection_questions_with_checkboxes
  end

  get "/maintenance" => "errors#maintenance", as: :maintenance_page
  match "/403", to: "errors#forbidden", as: :error_403, via: :all
  match "/404", to: "errors#not_found", as: :error_404, via: :all

app/models/report.rb
class Report < ActiveResource::Base
  self.site = Settings.forms_api.base_url
  self.prefix = "/api/v1/"
  self.include_format_in_path = false
  headers["X-API-Token"] = Settings.forms_api.auth_key
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :check_user_has_permission
  after_action :verify_authorized

  def index; end

  def features
    data = Report.find("features")

    render template: "reports/features", locals: { data: }
  end

  def users
    data = UsersReportService.new.user_data

    render locals: { data: }
  end

  def add_another_answer
    data = Report.find("features")

    render template: "reports/add_another_answer", locals: { data: }
  end

  def last_signed_in_at; end

  def selection_questions_summary
    data = Report.find("selection-questions-summary")

    render template: "reports/selection_questions/summary", locals: { data: }
  end

  def selection_questions_with_autocomplete
    data = Report.find("selection-questions-with-autocomplete")

    render template: "reports/selection_questions/autocomplete", locals: { data: }
  end

  def selection_questions_with_radios
    data = Report.find("selection-questions-with-radios")

    render template: "reports/selection_questions/radios", locals: { data: }
  end

  def selection_questions_with_checkboxes
    data = Report.find("selection-questions-with-checkboxes")

    render template: "reports/selection_questions/checkboxes", locals: { data: }
  end

private

  def check_user_has_permission
    authorize Report, :can_view_reports?
  end
end

app/views/reports/add_another_answer.html.erb
<% set_page_title(t(".title")) %>
<% content_for :back_link, govuk_back_link_to(reports_path, t("reports.back_link")) %>
<div class="govuk-grid-row">
  <div class="govuk-grid-column-two-thirds">
    <h1 class="govuk-heading-l"><%= t(".heading") %></h1>

    <h2 class="govuk-heading-m govuk-visually-hidden"><%= t(".heading") %></h2>
    <%= govuk_table do |table| %>

      <%= table.with_head do |head| %>
        <%= head.with_row do |row| %>
          <%= row.with_cell(text: t(".add_another_answer.table_headings.form_name")) %>
          <%= row.with_cell(text: t(".add_another_answer.table_headings.question_text")) %>
          <%= row.with_cell(text: t(".add_another_answer.table_headings.form_state")) %>
        <%end%>
      <%end%>
      <%= table.with_body do |body| %>
        <% data.all_forms_with_add_another_answer.sort_by(&:state).each do |form| %>
          <% form.repeatable_pages.each do |question| %>
            <%= body.with_row do |row| %>
              <%= row.with_cell(text: govuk_link_to(form.name, form_url(form.form_id))) %>
              <%= row.with_cell(text: question.question_text) %>
              <%= row.with_cell(text: form.state.capitalize.gsub("_", " ")) %>
            <%end%>
          <%end%>
        <%end%>
      <%end%>
    <%end%>
  </div>
</div>

app/views/reports/features.html.erb
<% set_page_title(t(".title")) %>
<% content_for :back_link, govuk_back_link_to(reports_path, t("reports.back_link")) %>
<div class="govuk-grid-row">
  <div class="govuk-grid-column-two-thirds">
    <h1 class="govuk-heading-l"><%= t(".title") %></h1>

    <h2 class="govuk-heading-m"><%= t(".features.heading") %></h2>
    <%= govuk_summary_list do |summary_list| %>
      <%= summary_list.with_row do |row| %>
        <%= row.with_key(text: t(".features.total_live_forms")) %>
        <%= row.with_value(text: data.total_live_forms) %>
      <% end %>
      <%= summary_list.with_row do |row| %>
        <%= row.with_key(text: t(".features.live_forms_with_routes")) %>
        <%= row.with_value(text: data.live_forms_with_routing) %>
      <% end %>
      <%= summary_list.with_row do |row| %>
        <%= row.with_key(text: t(".features.live_forms_with_payments")) %>
        <%= row.with_value(text: data.live_forms_with_payment) %>
      <% end %>
      <%= summary_list.with_row do |row| %>
        <%= row.with_key(text: t(".features.live_forms_with_add_another_answer")) %>
        <%= row.with_value(text: data.live_forms_with_add_another_answer) %>
      <% end %>
      <%= summary_list.with_row do |row| %>
        <%= row.with_key(text: t(".features.live_forms_with_csv_submission_enabled")) %>
        <%= row.with_value(text: data.live_forms_with_csv_submission_enabled) %>
      <% end %>
    <% end %>

    <h2 class="govuk-heading-m govuk-visually-hidden"><%= t(".answer_types.heading") %></h2>
    <%= govuk_table do |table| %>
      <%= table.with_caption(size: 'm', text: t(".answer_types.heading")) %>

      <%= table.with_head do |head| %>
        <%= head.with_row do |row| %>
          <%= row.with_cell(text: t(".answer_types.table_headings.answer_type")) %>
          <%= row.with_cell(text: t(".answer_types.table_headings.number_of_forms"), numeric: true) %>
          <%= row.with_cell(text: t(".answer_types.table_headings.number_of_pages"), numeric: true) %>
        <% end %>
      <% end %>

      <% answer_type_links = { selection: report_selection_questions_summary_path } %>
      <%= table.with_body do |body| %>
        <% Page::ANSWER_TYPES_INCLUDING_FILE.map(&:to_sym).each do |answer_type| %>
          <%= body.with_row do |row| %>
            <%= row.with_cell(header: true, text: t("helpers.label.page.answer_type_options.names.#{answer_type}")) %>
            <% if answer_type_links[answer_type].present? %>
              <%= row.with_cell(text: govuk_link_to(data.live_forms_with_answer_type.attributes[answer_type] || 0, answer_type_links[answer_type], no_visited_state: true), numeric: true, html_attributes: { data: { "live-forms-with-answer-type-#{answer_type.to_s.dasherize}": true } }) %>
            <% else %>
              <%= row.with_cell(text: data.live_forms_with_answer_type.attributes[answer_type] || 0, numeric: true, html_attributes: { data: { "live-forms-with-answer-type-#{answer_type.to_s.dasherize}": true } }) %>
            <% end %>
            <%= row.with_cell(text: data.live_pages_with_answer_type.attributes[answer_type] || 0, numeric: true, html_attributes: { data: { "live-pages-with-answer-type-#{answer_type.to_s.dasherize}": true } }) %>
          <% end %>
        <% end %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/reports/index.html.erb
<% set_page_title(t(".title")) %>
<div class="govuk-grid-row">
  <div class="govuk-grid-column-two-thirds">
    <h1 class="govuk-heading-l"><%= t(".title") %></h1>
    <ul class="govuk-list">
      <li><%= govuk_link_to t("reports.features.title"), report_features_path %></li>
      <li><%= govuk_link_to t("reports.users.title"), report_users_path %></li>
      <li><%= govuk_link_to t("reports.add_another_answer.title"), report_add_another_answer_path %></li>
      <li><%= govuk_link_to t("reports.last_signed_in_at.title"), report_last_signed_in_at_path %></li>
    </ul>
  </div>
</div>

app/views/reports/last_signed_in_at.html.erb
<% set_page_title(t(".title")) %>

<% content_for :back_link, govuk_back_link_to(reports_path, t("reports.back_link")) %>

<div class="govuk-grid-row">
  <div class="govuk-grid-column-two-thirds">
    <h1 class="govuk-heading-l"><%= t(".heading") %></h1>

    <% _1_year_ago = 1.year.ago.to_date.to_fs %>
    <%= render LastSignedInAtReportComponent::View.new(
      t(".not_since", since: _1_year_ago), User.where("last_signed_in_at <= ?", 1.year.ago),
    ) %>

    <%= render LastSignedInAtReportComponent::View.new(
      t(".not_since_last_signed_in_at_added"), User.where.not(provider: :gds).where(last_signed_in_at: nil),
    ) %>

    <%= render LastSignedInAtReportComponent::View.new(
      t(".not_since_auth0_enabled"), User.where(provider: :gds),
    ) %>
  </div>
</div>

app/views/reports/users.html.erb
<% set_page_title(t(".title")) %>
<% content_for :back_link, govuk_back_link_to(reports_path, t("reports.back_link")) %>
<div class="govuk-grid-row">
  <div class="govuk-grid-column-two-thirds">
    <h1 class="govuk-heading-l"><%= t(".title") %></h1>

    <%= govuk_table(**data) %>

  </div>
</div>